### ISSUE TITLE
Add resolutions higher than 1920x1080 ?

### ISSUE THREAD

**Issue by physkets** [stephenjsweeney/tbftss#49]
I have a monitor with a resolution of 2560x1440, while the maximum resolution I can set the game to is 1920x1080. Can you add more options for resolution, including mine? Thanks!

p.s. When I quit normally, the resolution of my desktop resets, but if the game crashes (when I clicked on `Challenges`) the desktop remains at 1920x1080.

**Comment by stephenjsweeney** [comment]
Adding more resolution is easy (just add them to data/widgets/options.json), although the game renders internally at 1280 x 720 and then scales up, meaning things will become blurry. Conversely, rendering at the requests resolution could mean things become too small.

Does the game always crash when you click Challenges? If possible, could you get me a stacktrace from gdb.

I would suggest for now that you run the game in a window, so that it doesn't lock up your display or mess with your resolution upon crashing (the develop branch has a new texture atlas feature and there might be bugs left to uncover).

**Comment by stephenjsweeney** [comment]
I've pushed a new update to `develop`, with the added resolutions. My laptop only goes up to 1920 x 1080, so those new resolutions aren't usable by me. If you could give them a go?

**Comment by physkets** [comment]
It is interesting that the internal rendering is de-coupled with the scalable display. Just a suggestion, but it would be a cool option, if you also allowed setting the rendering res. That way, people can choose to render at what their machine can handle, and set it to display at what their screen is meant to (of course if the disparity is too large, it will be blurry, but still). Is that possible?

Yes, selecting Challenges always makes it crash; running it in a terminal puts out the message: `Floating point exception`. I have this compiled without debug symbols, so gdb doesn't give any extra info, but let me see.

I'm trying it at 2560x1440, fullscreen, and it isn't too blurry. It is very playable.

**Comment by stephenjsweeney** [comment]
I've updated `develop` to allow for a -size switch to the specified. One can now do:
`-size 1600x900`, `-size 320x200`, etc. to get different screen resolutions. No error handling, so it's possible to crash it with incorrect formatting, but that can be fixed a bit later.

**Comment by stephenjsweeney** [comment]
Take a look at the new `resolution` branch. It's forked from `develop` so it should contain the other tweaks and fixes.

**Comment by stephenjsweeney** [comment]
Closing, as this issue is really old now and there's been on activity for many months.
