### ISSUE TITLE
Planets in background & star, planet based missions

### ISSUE THREAD

**Issue by Bertram25** [stephenjsweeney/tbftss#7]
Hey @stephenjsweeney ,

I've started playing the game and must say it's a real improvement over Project Starfighter. (I was the guy proposing the radar patch for that game at the time, btw.)

I've seen several missions where one can see a planet in the background on certain map points, and I would say that the fact that they move out of scope feels weird. The planets being big objects, the parallax effect should rather make them almost immobile. Just to point this out.

Second point, as mission are located around planet of solar systems, maybe certain of them could be done near a planet, meaning that the background would not only represent far away stars but also the space border of a planet. This would definitely improve immersion IMHO.

Good luck for the game(s)!

**Comment by stephenjsweeney** [comment]
Thanks for the comments! Glad you're enjoying the game.

I'm going to tweak the speed of the planet, so that it moves much more slowly. The idea wasn't to have it visible all the time, in order to add a little more atmosphere. It will still fall out of view if you travel far enough, however.

I could indeed make some missions be closer to a planet, however I would need to be careful of not running into some colour clashes, and making the planet's graphics obscure or mask things like bullets and missiles. I guess I could always make the planet darker or blur it appropriately.

**Comment by Bertram25** [comment]
> I'm going to tweak the speed of the planet, so that it moves much more slowly. The idea wasn't to have it visible all the time, in order to add a little more atmosphere. It will still fall out of view if you travel far enough, however.

Just tried the `develop` branch, the planets placement and movement has already improved! But they are drawn after the stardust, which make them look weird. (Noticed that in the sol 1st mission).

As for the other item, it will IMHO be a bit more difficult to do, but could improve immersion a lot!

Best!
